#!/bin/bash
cd /tmp/rom # Depends on where source got synced

#Some dependencies
sudo apt-get install python2 -y
sudo apt-get install cpio -y

# Normal build steps
python --version
. build/envsetup.sh
lunch omni_violet-eng
export LC_ALL="C"
export ALLOW_MISSING_DEPENDENCIES=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics



up(){
	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
	# 14 days, 10 GB limit
}

# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
# Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!

# Let's compile by parts! Coz of ram issue!
make api-stubs-docs || echo no problem
make hiddenapi-lists-docs || echo no problem
make system-api-stubs-docs || echo no problem
make test-api-stubs-docs || echo no problem

mka recoveryimage   # I used bacon build command
#sleep 85m # Lets give some space for uploading ccache
#kill %1 # better way to kill it!
up out/target/product/violet/*zip
ccache -s
#and dont use below codes for first 1 or 2 times, to get ccache uploaded,
#as instructed, i removed below lines temporarily. Will add those from 2nd or 3rd builds may be.
#yes
